[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mathz"
version = "0.1.0"
readme = "README.md"
authors = [
    { name = "Arthur Ryman", email = "arthur.ryman@gmail.com" }
]
