#!/bin/zsh
./mathz_categories/typecheck.sh
./mathz_complex_numbers/typecheck.sh
./mathz_core/typecheck.sh
./mathz_groups/typecheck.sh
./mathz_integers/typecheck.sh
./mathz_lie_groups_and_algebras/typecheck.sh
./mathz_manifolds/typecheck.sh
./mathz_real_numbers/typecheck.sh
./mathz_sets/typecheck.sh
./mathz_topological_spaces/typecheck.sh
./mathz_vector_spaces/typecheck.sh
