#!/bin/zsh
./mathz-categories/typecheck.sh
./mathz-complex-numbers/typecheck.sh
./mathz-core/typecheck.sh
./mathz-groups/typecheck.sh
./mathz-integers/typecheck.sh
./mathz-lie-groups-and-algebras/typecheck.sh
./mathz-manifolds/typecheck.sh
./mathz-real-numbers/typecheck.sh
./mathz-sets/typecheck.sh
./mathz-topological-spaces/typecheck.sh
./mathz-vector-spaces/typecheck.sh
